language: python
python:
  - "2.7"
# command to install dependencies
install:
- pip install pysam
- pip install biopython
# command to run tests
script:
  - time python merge_pcr_duplicates.py -o new_output.bed test-data/example_star1_input.bam  test-data/example_star1_input.fastq
  - diff test-data/example_star1_output.bed new_output.bed

